---

# Debian install tasks

- name: 'INSTALL | Install desired PHP packages'
  become: True
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ php_apt_update_cache }}"
    cache_valid_time: "{{ php_apt_cache_valid_time }}"
  notify: 'HANDLER | Manage dependencies services'
  with_items: "{{ php_packages }}"
