---

# Debian install tasks

- name : install desired php packages
  become : True
  apt  :
    name  : "{{ item }}"
    state : present
    update_cache: "{{ php_apt_update_cache }}"
    cache_valid_time: "{{ php_apt_cache_valid_time }}"
  register   : new_packages_installed
  notify: 'Manage dependencies services'
  with_items : "{{ php_packages }}"
