---

# Main tasks file for php role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::php'
    - 'role::php::config'
    - 'role::php::init'
    - 'role::php::install'


- name: 'INSTALL | Install PHP'
  include_tasks: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::php'
    - 'role::php::install'


- name: 'CONFIG | Configure PHP and modules'
  include_tasks: "{{ role_path }}/tasks/config.yml"
  tags:
    - 'role::php'
    - 'role::php::config'
