---

# Tasks file for php

- name: Load the OS specific varibles
  include_vars: "vars/{{ ansible_distribution_release | lower }}.yml"


- include: install_debian.yml
  tags:
    - install
    - php
  when: ansible_os_family == "Debian"


- include: 'config.yml'
  tags:
    - 'php::role'
    - 'php::config'


- name  : disable php modules
  become : True
  shell : "{{ php_modules_binary_disable }} {{ item.name }}"
  args  :
    removes : "{{ item.link }}"
  notify: 'Manage dependencies services'
  with_items : "{{ php_module_to_disable }}"


- name  : enable php modules
  become : True
  shell : "{{ php_modules_binary_enable }} {{ item.name }}"
  args  :
    creates : "{{ item.link }}"
  notify: 'Manage dependencies services'
  with_items : "{{ php_module_to_enable }}"
