---

# Tasks file for php

- name: 'Load the OS specific varibles'
  include_vars: "vars/{{ ansible_distribution_release | lower }}.yml"
  tags:
    - 'php::role'
    - 'php::config'
    - 'php::install'


- name: 'Install PHP on debian familly systems'
  include: 'install_debian.yml'
  when: "{{ (ansible_os_family | lower) == 'debian' }}"
  tags:
    - 'php::role'
    - 'php::install'


- name: 'Configure PHP and modules'
  include: 'config.yml'
  tags:
    - 'php::role'
    - 'php::config'
