---

# Debian tasks post install

- name    : restart web server
  become : True
  service :
    name  : "{{ php_webserver_service_name }}"
    state : restarted
  when : >
    php_webserver_service_name and
    (
      new_packages_installed.changed or
      php_config_change.changed      or
      php_module_enabled.changed     or
      php_module_disabled.changed
    )
