---

# handlers file for php

- name: 'Manage dependencies services'
  become: True
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ php_dependencies_services }}"
