---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "php-docker-xenial"
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "php-docker-trusty"
    image: 'ubuntu:trusty'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        php_config_settings:
          - dest: "{{ php_config_base_path }}/cli/php.ini"
            settings:
              - section: 'PHP'
                option: 'precision'
                value: 15
              - section: 'sqlite3'
                state: 'absent'
              - section: 'sqlite'
                state: 'absent'
        php_modules_enabled: "{{ _php_modules_enabled | difference(['json', 'opcache']) }}"
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
